version: '3'

services:
  rx-app:
    build: .
    depends_on:
      - redis
      - mongo
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_DATA_MONGODB_HOST: mongo
    command: java -jar rx.jar
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"